name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby (required for Ceedling)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Ceedling
        run: gem install ceedling

      - name: Run Ceedling tests
        run: |
          cd test_env
          ceedling test:all